### ISSUE TITLE
No excess property checks for nullary sums

### ISSUE THREAD

**Issue by Magellol** [unsplash/sum-types-fp-ts#3]
The following produces a runtime exception with no type errors.

```ts
import { getShow } from '@unsplash/sum-types-fp-ts';
import * as Sum from '@unsplash/sum-types';

type S = Sum.Member<'A'> | Sum.Member<'B'>;
const S = Sum.create<S>();

const show = getShow<S>({
  A: 'Custom',
});

console.log(show.show(S.mk.A));
```

https://stackblitz.com/edit/typescript-5afkt4?file=index.ts

I believe if supplied, `A` must be an instance of `Show` but TS doesn't check for it. 

Side note, I find it a little confusing prepending the sum member key in the show output here https://github.com/unsplash/sum-types-fp-ts/blob/master/src/index.ts#L153 . In the following code I'm expecting the show output to be `CustomA` but instead I get `A CustomerA`

```ts
const show = getShow<S>({
  A: {
    show: () => "CustomA"
  }  
});

```

**Comment by samhh** [comment]
This appears to only be an issue with nullary sums. Add any non-nullary member and `A` will be flagged as an unknown property.
